SIMULATION_RESULT_DIRECTORY = "./results"
PROFILING_RESULT_DIRECTORY = "./profiler_results"
LOGGING_RESULT_DIR = "./logs"
TRACE_DIRECTORY = "./cache_traces"
EVICTION_LOGGING_RESULT_DIRECTORY = f"{LOGGING_RESULT_DIR}/eviction/"
EXECUTION_LOGGING_RESULT_DIRECTORY = f"{LOGGING_RESULT_DIR}/execution/"

FILTER_ARGS = {
    "size": 1000000,
    "percentile": 90
}