SIMULATION_RESULT_DIRECTORY = "./results"
PROFILING_RESULT_DIRECTORY = "./profiler_results"
EVICTION_LOGGING_RESULT_DIRECTORY = "./logs/eviction/"
EXECUTION_LOGGING_RESULT_DIRECTORY = "./logs/execution/"